<a href="https://colab.research.google.com/github/NaveenKumar1209/ml/blob/main/Random_Forest_dec_27_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import sklearn
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import sklearn

In [ ]:
df = pd.read_csv("https://raw.githubusercontent.com/ezioauditore-tech/AI/main/datasets/Loan%20Status.csv");
df.head()

Loan_ID Gender Married Dependents     Education Self_Employed  \
0  LP001002   Male      No          0      Graduate            No   
1  LP001003   Male     Yes          1      Graduate            No   
2  LP001005   Male     Yes          0      Graduate           Yes   
3  LP001006   Male     Yes          0  Not Graduate            No   
4  LP001008   Male      No          0      Graduate            No   

   ApplicantIncome  CoapplicantIncome  LoanAmount  Loan_Amount_Term  \
0             5849                0.0         NaN             360.0   
1             4583             1508.0       128.0             360.0   
2             3000                0.0        66.0             360.0   
3             2583             2358.0       120.0             360.0   
4             6000                0.0       141.0             360.0   

   Credit_History Property_Area Loan_Status  
0             1.0         Urban           Y  
1             1.0         Rural           N  
2             1.0         Urban           Y  
3             1.0         Urban           Y  
4             1.0         Urban           Y

In [ ]:
df.describe()

ApplicantIncome  CoapplicantIncome  LoanAmount  Loan_Amount_Term  \
count       614.000000         614.000000  592.000000         600.00000   
mean       5403.459283        1621.245798  146.412162         342.00000   
std        6109.041673        2926.248369   85.587325          65.12041   
min         150.000000           0.000000    9.000000          12.00000   
25%        2877.500000           0.000000  100.000000         360.00000   
50%        3812.500000        1188.500000  128.000000         360.00000   
75%        5795.000000        2297.250000  168.000000         360.00000   
max       81000.000000       41667.000000  700.000000         480.00000   

       Credit_History  
count      564.000000  
mean         0.842199  
std          0.364878  
min          0.000000  
25%          1.000000  
50%          1.000000  
75%          1.000000  
max          1.000000

In [ ]:
df.isnull().sum()

Loan_ID               0
Gender               13
Married               3
Dependents           15
Education             0
Self_Employed        32
ApplicantIncome       0
CoapplicantIncome     0
LoanAmount           22
Loan_Amount_Term     14
Credit_History       50
Property_Area         0
Loan_Status           0
dtype: int64

In [ ]:
df.shape

(614, 13)

In [ ]:
type(df)

pandas.core.frame.DataFrame

In [ ]:
df.dtypes

Loan_ID               object
Gender                object
Married               object
Dependents            object
Education             object
Self_Employed         object
ApplicantIncome        int64
CoapplicantIncome    float64
LoanAmount           float64
Loan_Amount_Term     float64
Credit_History       float64
Property_Area         object
Loan_Status           object
dtype: object

In [ ]:
df.nunique()

Loan_ID              614
Gender                 2
Married                2
Dependents             4
Education              2
Self_Employed          2
ApplicantIncome      505
CoapplicantIncome    287
LoanAmount           203
Loan_Amount_Term      10
Credit_History         2
Property_Area          3
Loan_Status            2
dtype: int64

In [ ]:
df["ApplicantIncome"].unique()

array([ 5849,  4583,  3000,  2583,  6000,  5417,  2333,  3036,  4006,
       12841,  3200,  2500,  3073,  1853,  1299,  4950,  3596,  3510,
        4887,  2600,  7660,  5955,  3365,  3717,  9560,  2799,  4226,
        1442,  3750,  4166,  3167,  4692,  3500, 12500,  2275,  1828,
        3667,  3748,  3600,  1800,  2400,  3941,  4695,  3410,  5649,
        5821,  2645,  4000,  1928,  3086,  4230,  4616, 11500,  2708,
        2132,  3366,  8080,  3357,  3029,  2609,  4945,  5726, 10750,
        7100,  4300,  3208,  1875,  4755,  5266,  1000,  3333,  3846,
        2395,  1378,  3988,  2366,  8566,  5695,  2958,  6250,  3273,
        4133,  3620,  6782,  2484,  1977,  4188,  1759,  4288,  4843,
       13650,  4652,  3816,  3052, 11417,  7333,  3800,  2071,  5316,
        2929,  3572,  7451,  5050, 14583,  2214,  5568, 10408,  5667,
        2137,  2957,  3692, 23803,  3865, 10513,  6080, 20166,  2014,
        2718,  3459,  4895,  3316, 14999,  4200,  5042,  6950,  2698,
       11757,  2330,

In [ ]:

# one_hot_encoded_data = pd.get_dummies(df, columns = ['Education'])
# print(one_hot_encoded_data)

      Loan_ID  Gender Married Dependents Self_Employed  ApplicantIncome  \
0    LP001002    Male      No          0            No             5849   
1    LP001003    Male     Yes          1            No             4583   
2    LP001005    Male     Yes          0           Yes             3000   
3    LP001006    Male     Yes          0            No             2583   
4    LP001008    Male      No          0            No             6000   
..        ...     ...     ...        ...           ...              ...   
609  LP002978  Female      No          0            No             2900   
610  LP002979    Male     Yes         3+            No             4106   
611  LP002983    Male     Yes          1            No             8072   
612  LP002984    Male     Yes          2            No             7583   
613  LP002990  Female      No          0           Yes             4583   

     CoapplicantIncome  LoanAmount  Loan_Amount_Term  Credit_History  \
0                  0.0     

In [ ]:
# import numpy as np

# from sklearn. preprocessing import OneHotEncoder
# onehot_encoder =OneHotEncoder(sparse=False)
# df_1= np.array([df['Loan_Status']]).reshape(-1,1)
# data = onehot_encoder.fit_transform(df_1)
# data

/usr/local/lib/python3.10/dist-packages/sklearn/preprocessing/_encoders.py:868: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(


array([[0., 1.],
       [1., 0.],
       [0., 1.],
       ...,
       [0., 1.],
       [0., 1.],
       [1., 0.]])

In [ ]:
df["Gender"] = df["Gender"].map({"Male":1,"Female":0})
df["Married"] = df["Married"].map({"Yes":1,"No":0})
df["Education"] = df["Education"].map({"Graduate":1,"Not Graduate":0})
df["Dependents"].replace('3+', 3, inplace =True)
df["Self_Employed"]= df['Self_Employed'].map({'Yes':1,"No":0})
df["Property_Area"]=df["Property_Area"].map({'Semiurban':1,'Urban':2,'Rural':3})
df["Loan_Status"]=df["Loan_Status"].map({'Y' : 1,'N' : 0})


In [ ]:
rev_null =["Gender","Married","Dependents","Self_Employed","Credit_History","LoanAmount","Loan_Amount_Term","Property_Area","Loan_Status"]
df[rev_null]=df[rev_null].replace({
    np.nan:df['Gender'].mode(),
    np.nan:df['Married'].mode(),
    np.nan:df['Dependents'].mode(),
    np.nan:df['Self_Employed'].mode(),
    np.nan:df['Credit_History'].mode(),
     np.nan:df['LoanAmount'].mode(), np.nan:df['Loan_Amount_Term'].mode()
})

In [ ]:
X =df .drop(columns=['Loan_ID','Loan_Status']).values
y =df['Loan_Status'].values
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test =train_test_split(X,y,test_size=0.2,train_size=0.8)

In [ ]:
X_train

array([[0.0, 0.0, '0', ..., 360.0, 1.0, 1],
       [1.0, 0.0, '0', ..., 360.0, 0.0, 3],
       [0.0, 1.0, '0', ..., 360.0, 1.0, 1],
       ...,
       [0.0, 1.0, '0', ..., 360.0, 1.0, 2],
       [0.0, 0.0, '0', ..., 360.0, 1.0, 2],
       [0.0, 0.0, '0', ..., 360.0, 1.0, 3]], dtype=object)

In [ ]:
from sklearn.preprocessing import StandardScaler
from sklearn.impute import SimpleImputer
std =StandardScaler()
X_train = std.fit_transform(X_train)
X_test =std.transform(X_test)
imputer = SimpleImputer(strategy='mean')  # You can use 'median' or 'most_frequent' based on your preference
X_train = imputer.fit_transform(X_train)
X_test = imputer.transform(X_test)

In [ ]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report
rfc = RandomForestClassifier(criterion ='entropy',random_state =42 )
rfc.fit(X_train, y_train)

RandomForestClassifier(criterion='entropy', random_state=42)

In [ ]:

y_pred = rfc.predict(X_test)
print(classification_report(y_test, y_pred))


              precision    recall  f1-score   support

           0       0.70      0.46      0.56        41
           1       0.77      0.90      0.83        82

    accuracy                           0.76       123
   macro avg       0.74      0.68      0.70       123
weighted avg       0.75      0.76      0.74       123

